## 1st TEST

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

Devide the dataset into 3 buckets (bad < 4, 3 < medium < 8, good > 7), and train a BERT + classification.

In [2]:
# Load datasets
df_train = pd.read_csv("dataset/drugsComTrain_raw.csv", delimiter=',')
df_test  = pd.read_csv("dataset/drugsComTest_raw.csv", delimiter=',')

# Concatenate datasets
df = pd.concat([df_train, df_test], ignore_index=True, axis=0)

# Print shapes and head
print(f"Train shape: {df_train.shape}")
print(f"\nTest shape: {df_test.shape}")
print(f"\nCombined dataframe shape: {df.shape}")

df.head()

Train shape: (161297, 7)

Test shape: (53766, 7)

Combined dataframe shape: (215063, 7)

,uniqueID,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9,20-May-12,27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8,27-Apr-10,192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5,14-Dec-09,17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8,3-Nov-15,10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9,27-Nov-16,37

In [3]:
df.dtypes

uniqueID        int64
drugName       object
condition      object
review         object
rating          int64
date           object
usefulCount     int64
dtype: object

In [4]:
df['rating'].value_counts()

rating
10    68005
9     36708
1     28918
8     25046
7     12547
5     10723
2      9265
3      8718
6      8462
4      6671
Name: count, dtype: int64

In [5]:
bins = [0, 4, 8, 11]
labels = ['bad', 'medium', 'good']

df['label'] = pd.cut(df['rating'], bins=bins, labels=labels, right=False, include_lowest=True)

# Verify the ditribution
counts = df['label'].value_counts()
print(f"The label ditribution is : \n{counts}")

# 2. Idntify the label ith the lowest value count
min_label = counts.idxmin()
min_value = counts.min()

print(f"\nThe label ith the lowest samples is: '{min_label}' with {min_value} counts.")

The label ditribution is :
label
good      129759
bad        46901
medium     38403
Name: count, dtype: int64

The label ith the lowest samples is: 'medium' with 38403 counts.

In [6]:
# Under-sample categories to match the minority class
# We group by 'label' and take 'min_value' random samples from each group
df_balanced = df.groupby('label').apply(lambda x: x.sample(n=min_value, random_state=42))
df_balanced = df_balanced.reset_index(drop=True)

# Verify the result
print("New class distribution:")
print(df_balanced['label'].value_counts())
df_balanced.head()

New class distribution:
label
bad       38403
medium    38403
good      38403
Name: count, dtype: int64

C:\Users\PC\AppData\Local\Temp\ipykernel_4588\4206130655.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_balanced = df.groupby('label').apply(lambda x: x.sample(n=min_value, random_state=42))
C:\Users\PC\AppData\Local\Temp\ipykernel_4588\4206130655.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_balanced = df.groupby('label').apply(lambda x: x.sample(n=min_value, random_state=42))

,uniqueID,drugName,condition,review,rating,date,usefulCount,label
0,82646,Mepivacaine,Local Anesthesia,"""I had a bad reaction while having dental work...",1,26-May-11,3,bad
1,217917,Strattera,ADHD,"""For me this drug causede headaches everyday, ...",1,4-Nov-08,72,bad
2,136402,Mirvaso,Rosacea,"""I didn&#039;t have the severe side effects th...",3,16-Sep-14,17,bad
3,172060,Amitiza,"Constipation, Chronic","""Am taking maximum dosage and does not work fo...",2,4-Sep-11,18,bad
4,108987,Nexplanon,Birth Control,"""I&#039;ve been on nexplanon for almost 11 mon...",3,29-Jun-17,1,bad

In [9]:
# Define Features (X) and Target (y)
X = df_balanced['review']
y = df_balanced['label']

# Perform the split
X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size=0.2, 
    random_state=42, 
    stratify=y          # keep the 1:1:1 ratio is kept in both sets
)

# Verify the results
print(f"Training set size: {len(X_train)}")
print(f"Test set size: {len(X_test)}")

print("\nClass distribution in Training set:")
print(y_train.value_counts(normalize=True))

print("\nClass distribution in Test set:")
print(y_test.value_counts(normalize=True))

Training set size: 92167
Test set size: 23042

Class distribution in Training set:
label
bad       0.333341
medium    0.333330
good      0.333330
Name: proportion, dtype: float64

Class distribution in Test set:
label
medium    0.333348
good      0.333348
bad       0.333304
Name: proportion, dtype: float64

### DATASET PREPARATION

### MODEL ARCHITECTURE

### TRANING

### VALIDATION